# Generated by Django 2.2.20 on 2022-01-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Mumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex_type', models.CharField(choices=[('male', 'ذكر'), ('female', 'انثى')], max_length=15)),
                ('gruop', models.TextField(choices=[('1', 'الاولى'), ('2', 'الثانية'), ('3', 'الثالثه'), ('4', 'الرابعه'), ('5', 'الخامسه'), ('6', 'السادسه'), ('7', 'السابعة')], max_length=10)),
                ('published_at', models.DateField(auto_now=True)),
                ('id_num', models.IntegerField(default=1)),
                ('money', models.IntegerField(default=0)),
                ('data_sub', models.DateField(auto_now=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='jobs')),
            ],
        ),
    ]
