# Generated by Django 2.2.20 on 2022-01-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mumber',
            name='data_sub',
            field=models.DateField(),
        ),
    ]
